package org.swathisprasad.dynamodbdemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "LibraryCatalog")
public class LibraryCatalog implements Serializable {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String author;

    @DynamoDBRangeKey
    private String topic;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private int year;

}
